In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("taniaj/australian-election-2019-tweets")

print("Path to dataset files:", path)

print("Path to dataset files:", path)
import os

# List files in the dataset directory
print("Files in dataset directory:", os.listdir(path))

100%|██████████| 28.7M/28.7M [00:00<00:00, 169MB/s]

Extracting files...


Path to dataset files: /root/.cache/kagglehub/datasets/taniaj/australian-election-2019-tweets/versions/2
Path to dataset files: /root/.cache/kagglehub/datasets/taniaj/australian-election-2019-tweets/versions/2
Files in dataset directory: ['auspol2019.csv', 'location_geocode.csv']


downloading files from Kaggle

In [ ]:
import pandas as pd
csv_file = os.path.join(path, 'auspol2019.csv')
x = pd.read_csv(csv_file)
print(x.head())
x1 = x['full_text']
x = x.drop_duplicates()
print(x[0:10])

            created_at                   id  \
0  2019-05-20 09:13:44  1130401208756187136   
1  2019-05-20 09:13:43  1130401205367140357   
2  2019-05-20 09:13:33  1130401162782371841   
3  2019-05-20 09:13:29  1130401143551434753   
4  2019-05-20 09:13:23  1130401118666809345   

                                           full_text  retweet_count  \
0  After the climate election: shellshocked green...            0.0   
1  @narendramodi @smritiirani Coverage of indian ...            0.0   
2  @workmanalice Do you know if Facebook is relea...            0.0   
3  @vanbadham We all understand we have a compuls...            0.0   
4  Shares were mixed in Asia, with India and Aust...            0.0   

   favorite_count       user_id          user_name user_screen_name  \
0             0.0  9.248486e+07       PIPELINEPETE         jocksjig   
1             0.0  7.756474e+08    Narinder Parmar      nparmar1957   
2             0.0  5.687300e+04        Peter Wells       peterwells   
3     

loading the dataset

In [ ]:
import re
def removeht(text):
    result = []
    for word in text.split():
        if word.startswith('#') and len(word) > 1:
            word = list(word)
            word[1] = word[1].upper()
            word = ''.join(word)
            word = ' '.join(re.findall('[A-Z][^A-Z]*', word))
        result.append(word)
    return ' '.join(result)
def removeNE(text)  :
      text = re.sub(r'[^\x00-\x7F]',' ', text)
      return text
def removeURL(text) :
    text = re.sub(r'^https?:\/\/.*[\r\n]*', '', text)
    return text


these are the regex functions for removing hashtags, non english characters which are characters not found in the ascii table, and URLs.
for the hashtag removal, here is the source :
https://stackoverflow.com/questions/68448243/efficient-way-to-split-multi-word-hashtag-in-python

for non english characters :
https://stackoverflow.com/questions/8689795/how-can-i-remove-non-ascii-characters-but-leave-periods-and-spaces

for urls :
https://stackoverflow.com/questions/11331982/how-to-remove-any-url-within-a-string-in-python

In [ ]:
x['full_text'] = x['full_text'].apply(removeht)
x['full_text'] = x['full_text'].apply(removeNE)
x['full_text'] = x['full_text'].apply(removeURL)
print(x[0:10])




            created_at                   id  \
0  2019-05-20 09:13:44  1130401208756187136   
1  2019-05-20 09:13:43  1130401205367140357   
2  2019-05-20 09:13:33  1130401162782371841   
3  2019-05-20 09:13:29  1130401143551434753   
4  2019-05-20 09:13:23  1130401118666809345   
5  2019-05-20 09:13:21  1130401110882177029   
6  2019-05-20 09:12:57  1130401009782673408   
7  2019-05-20 09:12:28  1130400889997385728   
8  2019-05-20 09:12:04  1130400789694885888   
9  2019-05-20 09:11:47  1130400718026756102   

                                           full_text  retweet_count  \
0  After the climate election: shellshocked green...            0.0   
1  @narendramodi @smritiirani Coverage of indian ...            0.0   
2  @workmanalice Do you know if Facebook is relea...            0.0   
3  @vanbadham We all understand we have a compuls...            0.0   
4  Shares were mixed in Asia, with India and Aust...            0.0   
5  Australia's pollsters to review incorrect elec...    

this is applying the regex functions to the column that has the tweet texts.

In [ ]:
x3 = x['full_text'].tolist()
import random
for i in range(0,100) :
    j = random.randint(0,len(x3))
    print(x3[j])


We put the question forward to the public   who as leader of the Liberal Party, do you think would have given the Coalition the best chance to win this election? You voted @JulieBishopMP , here s her reaction. Aus Votes News https://t.co/ennxyjSvkr
Labor's tax policies 'highly progressive' with top 20% feeling most impact Ausvotes Auspol https://t.co/23ZAz917OH
Auspol https://t.co/bmuotqFhsd
The African National Congress Party has retained power in South Africa after winning the country's election. The ANC won 57.5 per... https://t.co/SdHeEEyG4X
Australia gets to vote?
Warringah bucked the trend because @TonyAbbottMHR is just plain nasty. Auspol https://t.co/FVpSDLf9QW
The chardonnay sippers have taken over the pub,changed the decor,music,menu,turned it into a yuppie wine bar and are now are left trying to figure out why the HiVis-beer drinkers have left to drink else where.But we came here to help them &amp; educate them about culture Auspol
Labor WILL win the next election IF they fi

The column containing the tweets is converted to a list. the next purpose is just a way to view some sample tweets, I can't view all of them since the dataset is too large, it takes random numbers within the range of 0 to the length of the list of tweets.

In [ ]:
h1 = "Australia"
h2 = "Parliament"
h3 = "Taxes"
h4 = "Vote"
h5 = "Democracy"
h6 = "AusPol"  #common abreviation for Australian politics found when looking at the tweets
h7 = "Election Night"
h8 = "Tax Policy"
h9 =  "Campaign Promise"
h10 = "Climate Change"
hashtags = [h1,h2,h3,h4,h5,h6,h7,h8,h9,h10]








These are the hashtags.

This is a function to search for each hashtag, the tweets containing the hashtag, and the frequencies for each tweet has for a hashtag. All the tweets containing the hashtags are put in a big dictionary, then after finishing the search for each hashtag, the top 5 by frequency are added to a list for the top 5 for each hashtag. This list contains a list containing the hashtag name, the tweet, and the frequency. At the end, the list of top5s are printed in an organized manner. Since some of the hashtags got no results, in that case, it returns none found.

There was no lower case in the instructions for this part, so There were not as many results as expected for Australia. The multiword hashtags did not get any because the hashtags did not contain spaces within the phrases so it was unlikely for them to found the way they were written.  
But with spaces added and caps are altered with, the results do change.


In [ ]:
import spacy
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

# get a list of stopwords from NLTK
stops = set(stopwords.words('english'))

# Load SpaCy English language model
# this is apipeline capable of applying morphological, lexical and syntax analysis on text

nlp_pipeline = spacy.load("en_core_web_sm")

def pre_process_a_single_sentence(sentence):
  # Lower case text
  sentence = sentence.lower()

  processed_sentence = []

  # Tokenize, and lemmatize the text
  doc = nlp_pipeline(sentence)

  for token in doc:
    # here token is an object that contains various information about each token
    # information such as lemma, pos, parse labels are available

    # we will check here if tokens are present in stopwords
    # if not, we will retain their lemma
    if token not in stops:
      lemmatized_token = token.lemma_
      processed_sentence.append(lemmatized_token)
  processed_sentence = " ".join (processed_sentence)
  return processed_sentence

pre_processed_corpus = [pre_process_a_single_sentence(sentence) for sentence in x3]

import pickle

with open('preprocessed_corpus.pkl', 'wb') as file:
       pickle.dump(pre_processed_corpus, file)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


this pre-processes the data through lowercasing, tokenization, and lemmatization

In [1]:
import pickle
with open('preprocessed_corpus.pkl', 'rb') as file:
       pre_processed_corpus = pickle.load(file)

this creates a way to store the pre-processed data that way with each run, I won't have to go through pre-processing again.

In [ ]:
print (pre_processed_corpus[:15])

['after the climate election : shellshocke green group remain resolute https://t.co/wyjzmacyid', '@narendramodi @smritiirani coverage of indian election on sbs tv channel , australia . jai hind      https://t.co/90qplbeaf8', '@workmanalice do you know if facebook be release an election post - mortem in australia ? they look into the midterm , but be we important enough to bother ?', '@vanbadham we all understand we have a compulsory preference system . vote 1 mightn t go to the major but 2 or 3 usually do . majority of australia want lnp , that s the fact . this be nothing like the usa system .', 'share be mix in asia , with india and australia lead gain for the region follow election that looked set to keep incumbent in office . https://t.co/krrhpyurid', "australia 's pollster to review incorrect election forecast https://t.co/isy2spg7l5", 'it be disappointing that @tanya_plibersek have rule herself out of the @australianlabor leadership challenge - give her quality https://t.co/n1dai

In [74]:
print(len(pre_processed_corpus))




183371
183371


In [67]:
import random
size = 1000
corpus = random.sample(pre_processed_corpus, size)

this reduces the size of the data since there are over 100,000 tweets, vectorizing all of them forces the session to crash, so reducing the size makes it go much quicker.

In [52]:
print(corpus[:20])

['... no . ausvotes auspol https://t.co/kfrkvcppgj', 'yep , that be what I be hear during campaign from people here in qld   the negative tax message , particularly the noise about the retirement tax , do seem to cut through ,   a senior queensland labor figure say australia decide https://t.co/odsp7zb256', 'there be a hidden campaign of   immeasurable size be fight this election in the post - truth , largely unregulated battleground auspol https://t.co/wjzpgodhdr', 'here be a song by jenny talia of australia , which sum up the way many ppl in australia feel today about an    & amp ; malevolent govt allow 2 multi billionaire to hijack our democracy for their own self interest .    auspol https://t.co/vkpakwgm9y', 'in a taxi head to ellenbrook - @cporterwa country . pearce be another marginal wa seat that shorten would love to win . 6 month ago porter be go . today , goss be that he will scrape in . why a taxi ? one must improvise . it s ok . I ve train for this . wapol auspol ausvote',

In [68]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Define the N for N-grams
N = 1  # Change this to the desired value for N-grams

# Initialize the CountVectorizer with N-gram range
vectorizer = CountVectorizer(ngram_range=(N, N), lowercase = True, binary = False)

# Fit and transform the corpus
vectorizer.fit(corpus)

# Check a few items in the vocabulary
vocab = vectorizer.get_feature_names_out()

print (vocab)


['000' '001' '002' ... 'zyq7nbts7r' 'zyuawzpbgu' 'zzo0nf2bpl']


this initializes count vectorizor, this is Bag of Words, lower is true to ensure hashtag can get read.

In [69]:
print (vocab)

['000' '001' '002' ... 'zyq7nbts7r' 'zyuawzpbgu' 'zzo0nf2bpl']


In [23]:
h1 = "#Australia"
h2 = "#Parliament"
h3 = "#Party"
h4 = "#Government"
h5 = "Democracy"
h6 = "#AustralianPolitics"  #common abreviation for Australian politics found when looking at the tweets
h7 = "#ElectionNight"
h8 = "#PrimeMinister"
h9 =  "#CampaignPromise"
h10 = "#ClimateChange"
hashtags = [h1,h2,h3,h4,h5,h6,h7,h8,h9,h10]
import re
def rep(m):
    s=m.group(1)
    return ' '.join(re.split(r'(?=[A-Z])', s))

for a in range(0,len(hashtags)) :
    hashtags[a] = re.sub(r'#(\w+)', rep, hashtags[a])
print(hashtags)

[' Australia', ' Parliament', ' Party', ' Government', 'Democracy', ' Australian Politics', ' Election Night', ' Prime Minister', ' Campaign Promise', ' Climate Change']


these are the hashtags and in this they are if having two words have a space added.

In [70]:
bow_transformed_corpus = []

for sentence in corpus:
  transformed_vector = vectorizer.transform([sentence])
  bow_transformed_corpus.append(transformed_vector.toarray()[0])

qs = []
for a in hashtags :
    tv = vectorizer.transform([a])
    qs.append(tv.toarray()[0])
    print(tv.toarray()[0])


# sanity check : print a few items from the bow_transformed_corpus and bow_transformed_query

print()
print(qs)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]

[array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0])]


In [110]:
print(qs[0])

[0 0 0 ... 0 0 0]


In [56]:
import numpy as np
if np.array_equal(qs[1], qs[0]):
    print("yes")
else :
    print("no")


no


this is just to check to verify if the query vectors are the exact same or not

In [27]:
import numpy as np
def euclidean_distance_based_similarity (vector1, vector2):
    """
    Compute the Euclidean distance between two vectors.

    Parameters:
        vector1 (array-like): First vector.
        vector2 (array-like): Second vector.

    Returns:
        float: Euclidean distance between the two vectors.
    """
    return 1 / (np.linalg.norm(np.array(vector1) - np.array(vector2)))


similarity_scores = {}




all_query_results = {}





In [71]:
def sims(j) :
    query_vector = qs[j]
    similarity_scores = {}
    for i, document_vector in enumerate(bow_transformed_corpus):
        sim = euclidean_distance_based_similarity(document_vector, query_vector)
        similarity_scores[i] = sim
    ranked_documents = sorted(similarity_scores.items(),key = lambda x: x[1] ,reverse = True)


    print (f"Query:{hashtags[j]} ")
    for document_idx, score in ranked_documents[:10]:
      print (f"Document: {corpus[document_idx]}, Score: {score}")
for i in range(0,len(qs)) :
    print(sims(i))

Query: Australia 
Document: , Score: 1.0
Document: , Score: 1.0
Document: idiot auspol, Score: 0.5773502691896258
Document:        it begin        auspol, Score: 0.5
Document: ffs straya auspol, Score: 0.5
Document: hahahahahaha aus votes, Score: 0.5
Document:                       https://t.co/wtwp2gujzr                                                                          , Score: 0.5
Document: @vanonselenp australia have lose the election ., Score: 0.4472135954999579
Document: chisholm to labor auspol, Score: 0.4472135954999579
Document: auspol https://t.co/0q6k4qvzcl, Score: 0.4472135954999579
None
Query: Parliament 
Document: , Score: 1.0
Document: , Score: 1.0
Document: idiot auspol, Score: 0.5773502691896258
Document:        it begin        auspol, Score: 0.5
Document: ffs straya auspol, Score: 0.5
Document: hahahahahaha aus votes, Score: 0.5
Document:                       https://t.co/wtwp2gujzr                                                                          , Scor

observations :

The results were far too similar, they were not the exact same which is somewhat encouraging in the sense that there is no error causing the ranked documents to be the exact same for all queries but the difference is negligble as the scores for some not all were slightly different but the tweets were the exact same. For example, climate change has the exact same results as campaign promise, which does not make sense, and the results are the same for the other hashtags.

In [72]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Define the N for N-grams
N = 1  # Change this to the desired value for N-grams

# Initialize the CountVectorizer with N-gram range
vectorizer = TfidfVectorizer(ngram_range=(N, N), lowercase = True, binary = False)

# Fit and transform the corpus
vectorizer.fit(corpus)

# Check a few items in the vocabulary
vocab = vectorizer.get_feature_names_out()

This is initializing the TfIDF vectorizor. It is in lower to ensure the hashtags can get read.

In [74]:
bow_transformed_corpus = []

for sentence in corpus:
  transformed_vector = vectorizer.transform([sentence])
  bow_transformed_corpus.append(transformed_vector.toarray()[0])

qs = []
for a in hashtags :
    qs.append(vectorizer.transform([a]).toarray()[0])


print ("Transformed Corpus Samples", bow_transformed_corpus[:5])
print(qs)

Transformed Corpus Samples [array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])]
[array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])]


In [45]:
import numpy as np
if np.array_equal(qs[1], qs[0]):
    print("yes")
else :
    print("no")

no


In [75]:
def sims(j) :
    query_vector = qs[j]
    similarity_scores = {}
    for i, document_vector in enumerate(bow_transformed_corpus):
        sim = euclidean_distance_based_similarity(document_vector, query_vector)
        similarity_scores[i] = sim
    ranked_documents = sorted(similarity_scores.items(),key = lambda x: x[1] ,reverse = True)


    print (f"Query:{hashtags[j]} ")
    for document_idx, score in ranked_documents[:10]:
      print (f"Document: {corpus[document_idx]}, Score: {score}")
for i in range(0,len(qs)) :
    print(sims(i))

Query: Australia 
Document: , Score: 1.0
Document: , Score: 1.0
Document: @lydiajmeredith and australia can a vote be swe to australia, Score: 0.9061274187321869
Document: c m n now | australia the govern coalition in australia appear set for a surprise victory in a close - fight election . australia decide aus votes2019 @scottmorrisonmp, Score: 0.8781053369748851
Document: meanwhile in australia ausvotes australia decide election2019 result https://t.co/cidsvuhm6v, Score: 0.8728275261897526
Document: live election result australia 2019 : track the vote | australia news | the guardian https://t.co/bd46azpmpn, Score: 0.8499939147311432
Document: @vanonselenp australia have lose the election ., Score: 0.830843062018672
Document: look , I know the racist of australia be spoil for choice at the auspol poll but the   love australia or leave   party s icon just be an outline of australia with the word full inside it be fuck hilarious, Score: 0.8257174215506815
Document: whatever happen in au

results here were better, they were not the exact same, there were different results which is an improvement from using the Bag of Words method. This method got different search results and the results are also related to the hashtag. This is a massive improvement from the first.

In [61]:
from gensim.models import KeyedVectors  # task3
import gensim.downloader as api
import numpy as np

# Load pre-trained GloVe embeddings
word_vectors = api.load("glove-wiki-gigaword-50")

# Function to generate average word vectors for a sentence
def average_word_embeddings(sentence):
    words = sentence.split()
    embeddings = []
    for word in words:
        if word in word_vectors:
            embeddings.append(word_vectors[word])
    if len(embeddings) > 0:
        # is word vector exists for the word
        return np.mean(embeddings, axis=0)
    else:
        return np.zeros(word_vectors.vector_size)

In [79]:
def giga50(n):
    word_vector_transformed_corpus = []

    for sentence in corpus:
        transformed_vector = average_word_embeddings(sentence)
        word_vector_transformed_corpus.append(transformed_vector)

    word_vector_transformed_query = average_word_embeddings(hashtags[n].lower())



    word_vector_based_similarity_scores = {}

    for i, vector in enumerate(word_vector_transformed_corpus):
        sim = euclidean_distance_based_similarity(vector, word_vector_transformed_query)
        word_vector_based_similarity_scores[i] = sim

    ranked_documents = sorted(word_vector_based_similarity_scores.items(), key=lambda x: x[1], reverse=True)



    print(f"Query: {hashtags[n]}")
    for document_idx, score in ranked_documents[:10]:
        print(f"Document: {corpus[document_idx]}, Score: {score}")




for i in range(1,len(hashtags)) :
    print(giga50(i))

Query:  Parliament
Document: vote labor auspol ausvotes bill shorten vote for change https://t.co/eoggv1qy9w, Score: 0.1600116585642951
Document: vote u.a.g.p heck the rest . australia politics politicalmemes gamer gamermeme tasmania vote liberal liberalmeme primeminist election labour labourmeme green greensmeme onenation @scottmorrisonmp @billshortenmp @senatorpaulinehanson https://t.co/rci7qpffjv, Score: 0.15959928490699735
Document: australia 's conservative coalition poise to secure outright parliamentary majority - analyst https://t.co/xxzjcbvwnu https://t.co/hloqyepo5 g, Score: 0.15952470711804398
Document: the guardian view on the australian election : vote on the climate emergency climate election auspol ausvote https://t.co/xulpjj1onb, Score: 0.1575696748221534
Document: break : former prime minister @tonyabbottmhr have lose his seat of warringah after 25 year in parliament and public life . ausvotes n e w s https://t.co/ckeiiisica, Score: 0.1570899903850216
Document: austral

The results here are better than the TF_IDF vectorizor where the best results were not the empty string, and the rsults are not bad although the scores are not all that high.

In [63]:
word_vectors = api.load("glove-wiki-gigaword-200")

# Function to generate average word vectors for a sentence
def average_word_embeddings(sentence):
    words = sentence.split()
    embeddings = []
    for word in words:
        if word in word_vectors:
            embeddings.append(word_vectors[word])
    if len(embeddings) > 0:
        # is word vector exists for the word
        return np.mean(embeddings, axis=0)
    else:
        return np.zeros(word_vectors.vector_size)

[==================================================] 100.0% 252.1/252.1MB downloaded


In [78]:
def giga200(n):
    word_vector_transformed_corpus = []

    for sentence in corpus:
        transformed_vector = average_word_embeddings(sentence)
        word_vector_transformed_corpus.append(transformed_vector)

    word_vector_transformed_query = average_word_embeddings(hashtags[n].lower())



    word_vector_based_similarity_scores = {}

    for i, vector in enumerate(word_vector_transformed_corpus):
        sim = euclidean_distance_based_similarity(vector, word_vector_transformed_query)
        word_vector_based_similarity_scores[i] = sim

    ranked_documents = sorted(word_vector_based_similarity_scores.items(), key=lambda x: x[1], reverse=True)



    print(f"Query: {hashtags[n]}")
    for document_idx, score in ranked_documents[:10]:
        print(f"Document: {corpus[document_idx]}, Score: {score}")




for i in range(1,len(hashtags)) :
    print(giga200(i))

Query:  Parliament
Document: vote labor auspol ausvotes bill shorten vote for change https://t.co/eoggv1qy9w, Score: 0.1600116585642951
Document: vote u.a.g.p heck the rest . australia politics politicalmemes gamer gamermeme tasmania vote liberal liberalmeme primeminist election labour labourmeme green greensmeme onenation @scottmorrisonmp @billshortenmp @senatorpaulinehanson https://t.co/rci7qpffjv, Score: 0.15959928490699735
Document: australia 's conservative coalition poise to secure outright parliamentary majority - analyst https://t.co/xxzjcbvwnu https://t.co/hloqyepo5 g, Score: 0.15952470711804398
Document: the guardian view on the australian election : vote on the climate emergency climate election auspol ausvote https://t.co/xulpjj1onb, Score: 0.1575696748221534
Document: break : former prime minister @tonyabbottmhr have lose his seat of warringah after 25 year in parliament and public life . ausvotes n e w s https://t.co/ckeiiisica, Score: 0.1570899903850216
Document: austral

the scores are not not high here, but the results do relate to the hashtags, but not all , and they also got the same results as the gigaword-50 embedder.

In [65]:
word_vectors = api.load("glove-wiki-gigaword-300")

# Function to generate average word vectors for a sentence
def average_word_embeddings(sentence):
    words = sentence.split()
    embeddings = []
    for word in words:
        if word in word_vectors:
            embeddings.append(word_vectors[word])
    if len(embeddings) > 0:
        # is word vector exists for the word
        return np.mean(embeddings, axis=0)
    else:
        return np.zeros(word_vectors.vector_size)

[==================================================] 100.0% 376.1/376.1MB downloaded


In [76]:
def giga300(n):
    word_vector_transformed_corpus = []

    for sentence in corpus:
        transformed_vector = average_word_embeddings(sentence)
        word_vector_transformed_corpus.append(transformed_vector)

    word_vector_transformed_query = average_word_embeddings(hashtags[n].lower())



    word_vector_based_similarity_scores = {}

    for i, vector in enumerate(word_vector_transformed_corpus):
        sim = euclidean_distance_based_similarity(vector, word_vector_transformed_query)
        word_vector_based_similarity_scores[i] = sim

    ranked_documents = sorted(word_vector_based_similarity_scores.items(), key=lambda x: x[1], reverse=True)



    print(f"Query: {hashtags[n]}")
    for document_idx, score in ranked_documents[:10]:
        print(f"Document: {corpus[document_idx]}, Score: {score}")




for i in range(1,len(hashtags)) :
    print(giga300(i))

Query:  Parliament
Document: vote labor auspol ausvotes bill shorten vote for change https://t.co/eoggv1qy9w, Score: 0.1600116585642951
Document: vote u.a.g.p heck the rest . australia politics politicalmemes gamer gamermeme tasmania vote liberal liberalmeme primeminist election labour labourmeme green greensmeme onenation @scottmorrisonmp @billshortenmp @senatorpaulinehanson https://t.co/rci7qpffjv, Score: 0.15959928490699735
Document: australia 's conservative coalition poise to secure outright parliamentary majority - analyst https://t.co/xxzjcbvwnu https://t.co/hloqyepo5 g, Score: 0.15952470711804398
Document: the guardian view on the australian election : vote on the climate emergency climate election auspol ausvote https://t.co/xulpjj1onb, Score: 0.1575696748221534
Document: break : former prime minister @tonyabbottmhr have lose his seat of warringah after 25 year in parliament and public life . ausvotes n e w s https://t.co/ckeiiisica, Score: 0.1570899903850216
Document: austral

The results here from what I see are mostly the same, the scores may be different and the orders might possibly be different, but the results showing up in the top 10 seem the same.